export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const LEADERBOARD_LOADING = "LEADERBOARD_LOADING";
export const LEADERBOARD_SUCCESS = "LEADERBOARD_SUCCESS";
export const LEADERBOARD_FAILURE = "LEADERBOARD_FAILURE";

export const USER_LOADING = "USER_LOADING";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";

export const SAVED_LOADING = "SAVED_LOADING";
export const SAVED_SUCCESS = "SAVED_SUCCESS";
export const SAVED_FAILURE = "SAVED_FAILURE";

export const SAVING_LOADING = "SAVING_LOADING";
export const SAVING_SUCCESS = "SAVING_SUCCESS";
export const SAVING_FAILURE = "SAVING_FAILURE";

export const DELETE_LOADING = "DELETE_LOADING";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";

export const TOGGLE_NAV = "TOGGLE_NAV";
